//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvgToolsLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SvgToolsLib.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;pattern&gt;controlstyle(-\d+){0,1})).
        /// </summary>
        internal static string rxControlStyleName {
            get {
                return ResourceManager.GetString("rxControlStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;number&gt;-{0,1}[0-9]+(\.[0-9]*){0,1})(?&lt;measure&gt;[a-z\%]*).
        /// </summary>
        internal static string rxCssNumberWithMeasure {
            get {
                return ResourceManager.GetString("rxCssNumberWithMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url\(#(?&lt;name&gt;[^\)]+)\).
        /// </summary>
        internal static string rxCssUrlName {
            get {
                return ResourceManager.GetString("rxCssUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;field&gt;\{(?&lt;name&gt;[^\}]+)\}).
        /// </summary>
        internal static string rxEmbeddedFieldName {
            get {
                return ResourceManager.GetString("rxEmbeddedFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:[^0-9a-z-\.]*(?&lt;param&gt;([a-z]+|-{0,1}\d+(\.\d+){0,1}(e-{0,1}\d+){0,1}))[^0-9a-z-\.]*)).
        /// </summary>
        internal static string rxFindSvgTransformParams {
            get {
                return ResourceManager.GetString("rxFindSvgTransformParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:(?&lt;command&gt;(?&lt;name&gt;[a-z]+)\s*\(\s*(?&lt;params&gt;[^\)]*)\s*\)))).
        /// </summary>
        internal static string rxFindSvgTransforms {
            get {
                return ResourceManager.GetString("rxFindSvgTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;intent&gt;[a-z]+)(-(?&lt;reference&gt;[a-z]+[0-9a-z_ ]*)){0,1}).
        /// </summary>
        internal static string rxIntentWithReference {
            get {
                return ResourceManager.GetString("rxIntentWithReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?s:line\s+(?&lt;line&gt;\d+).*?position\s+(?&lt;position&gt;\d+))).
        /// </summary>
        internal static string rxJsonErrorLinePosition {
            get {
                return ResourceManager.GetString("rxJsonErrorLinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;name&gt;[a-z]+)\s*=\s*\&quot;(?&lt;value&gt;[^\&quot;]+)\&quot;).
        /// </summary>
        internal static string rxNameEqualsValue {
            get {
                return ResourceManager.GetString("rxNameEqualsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;nodeExtensionAssignment&gt;(?&lt;=^\w+-|;)(?&lt;name&gt;\w+)\:(?&lt;value&gt;[^\:\;]+))).
        /// </summary>
        internal static string rxNodeExtensionAssignment {
            get {
                return ResourceManager.GetString("rxNodeExtensionAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;number&gt;\d+).
        /// </summary>
        internal static string rxNumber {
            get {
                return ResourceManager.GetString("rxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;pattern&gt;-{0,1}[0-9]+(\.[0-9]+){0,1}(e-{0,1}[0-9]+){0,1})).
        /// </summary>
        internal static string rxNumeric {
            get {
                return ResourceManager.GetString("rxNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;pre&gt;.*?)(?&lt;seed&gt;\d+)(?&lt;post&gt;.*)$.
        /// </summary>
        internal static string rxNumericalSeed {
            get {
                return ResourceManager.GetString("rxNumericalSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:(?&lt;attribute&gt;(?&lt;name&gt;[^\:]+)\s*(\:\s*(?&lt;value&gt;[^\;]+)\;{0,1}){0,1}\s*))).
        /// </summary>
        internal static string rxStyleEntries {
            get {
                return ResourceManager.GetString("rxStyleEntries", resourceCulture);
            }
        }
    }
}
